---
title: "Methodology for “Accelerating the Open Research agenda to solve global challenges"
author: "Zuzanna B Zagrodzka, Andrew P Beckerman, Thomas F Johnson"
date: "`r Sys.Date()`"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

1. Data and Data pre-processing

- All mission statements (raw text data) are in the `./data/mission_statements` folder as txt files.
- All dictionary data are in the `./data/dictionaries` folder.
- [List of the organisations](ListMissionVision.html)
- [Dictionaries_preparation](1b_Dictionaries_preparation.html)
- [Data_preprocessing](1a_Data_preprocessing.html)

2. [Methodology - Topic modelling- analysis](2_Topic_modeling.html)
3. [Methodology - Topic modeling - produce Fig 2A](Figure_2A.html)
4. [Methodology - Text similarities - analysis and Fig 2B](3_Text_similarities_Figure_2B.html)
5. [Methodology - Language usage - analysis and Fig 2C](4_Language_analysis_Figure_2C.html)
6. [Methodology - For and Not-for-Profit publishers, OA and non-OA journals Assessment - dictionary analysis](5_For_and_not_for_profit_comparison.html)
7. [Methodology - For and Not-for-Profit publishers, OA and non-OA journals Assessment - topic analysis](6_Subgroups_comparison_text_similarities.html)
8. [Methodology - For and Not-for-Profit, OA and non-OA journals Assessment - dictionary analysis](7_For_and_not_for_profit_comparison_part_2.html)
9. [Methodology - For and Not-for-Profit, OA and non-OA journals Assessment - topic analysis](8_Subgroups_comparison_text_similarities_part_2.html)
10. [Methodology - Figure ilustrating journals owned by societies](9_Journals_additional_info.html)
11. [Licence](license.html)
12. [Additional Information - Session Info](Original_Session_Info.html)

<!-- wflow_publish("analysis/_site.yml", "Change the theme", republish = TRUE) -->


