---
title: "Original_Session_Info"
author: "ZZ, TFJ, APB"
date: "2023-11-09"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


All datasets that we created and used in our analysis are available in the "./data/original_dataset_reproducibility_check/" folder.


### Session Info of the original project

R version 4.0.3 (2020-10-10)

Platform: x86_64-apple-darwin17.0 (64-bit)

Running under: macOS Big Sur 10.16


Matrix products: default

BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib

LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib


locale:
en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8


List of the packages with versions that were used to create the original datasets:

- kableExtra_1.3.4
- tidytext_0.3.2
- forcats_0.5.1
- stringr_1.4.0
- dplyr_1.0.7
- purrr_0.3.4
- readr_2.0.2
- tidyr_1.1.4
- tibble_3.1.6
- ggplot2_3.3.5
- tidyverse_1.3.1
- workflowr_1.7.0
- fs_1.5.0
- lubridate_1.7.10
- bit64_4.0.5
- webshot_0.5.2
- httr_1.4.2
- rprojroot_2.0.2
- SnowballC_0.7.0
- tools_4.0.3
- backports_1.2.1
- bslib_0.3.0
- utf8_1.2.2
- R6_2.5.1
- DBI_1.1.1
- colorspace_2.0- 2
- withr_2.4.2
- tidyselect_1.1.1
- processx_3.5.2
- bit_4.0.4
- compiler_4.0.3
- git2r_0.29.0
- cli_3.1.0
- rvest_1.0.1
- xml2_1.3.2
- labeling_0.4.2
- sass_0.4.0
- scales_1.1.1
- callr_3.7.0
- systemfonts_1.0.22
- digest_0.6.28
- rmarkdown_2.11
- svglite_2.0.0
- pkgconfig_2.0.3
- htmltools_0.5.2
- dbplyr_2.1.1
- fastmap_1.1.0
- highr_0.9
- rlang_0.4.12
- readxl_1.3.1
- rstudioapi_0.13
- farver_2.1.0
- jquerylib_0.1.4
- generics_0.1.1
- jsonlite_1.7.2
- vroom_1.5.5
- tokenizers_0.2.1
- magrittr_2.0.3
- Matrix_1.3- 4
- Rcpp_1.0.7
- munsell_0.5.0
- fansi_0.5.0
- lifecycle_1.0.1
- stringi_1.7.5
- whisker_0.4
- yaml_2.2.1
- grid_4.0.3
- parallel_4.0.3
- promises_1.2.0.1
- crayon_1.4.2
- lattice_0.20- 45
- haven_2.4.3
- hms_1.1.1
- knitr_1.36
- ps_1.6.0
- pillar_1.6.4
- reprex_2.0.1
- glue_1.5.0
- evaluate_0.14
- getPass_0.2- 2
- modelr_0.1.8
- vctrs_0.3.8
- tzdb_0.1.2
- httpuv_1.6.3
- cellranger_1.1.0
- gtable_0.3.0
- assertthat_0.2.1
- xfun_0.31
- broom_0.7.9
- janeaustenr_0.1.5
- later_1.3.0
- viridisLite_0.4.08
- ellipsis_0.3.2
- stm_1.3.6
- ggraph_2.0.5
- igraph_1.2.6
- reshape2_1.4.4
- wordcloud_2.6
- RColorBrewer_1.1- 2
- topicmodels_0.2- 12
- tm_0.7- 8
- NLP_0.2- 1
- quanteda.dictionaries_0.3
- quanteda.textplots_0.94
- quanteda_3.1.0
- modeltools_0.2- 23
- graphlayouts_0.7.1
- ggrepel_0.9.1
- polyclip_1.10- 0
- ggforce_0.3.3
- tweenr_1.0.2
- fastmatch_1.1- 3
- slam_0.1- 48
- lexicon_1.2.1
- stopwords_2.3
- MASS_7.3- 54
- tidygraph_1.2.0
- gridExtra_2.3
- systemfonts_1.0.2
- processx_3.5.2
- tidyselect_1.1.1
- plyr_1.8.6
- viridis_0.6.1
- syuzhet_1.0.6
- data.table_1.14.2
- callr_3.7.0
- RcppParallel_5.1.4
- stats4_4.0.3
- viridisLite_0.4.0
- ggvenn_0.1.9
- ggalt_0.4.0
- ggtern_3.3.5
- compositions_2.0- 2
- ggwordcloud_0.5.0
- gutenbergr_0.2.1
- extrafont_0.17
- robustbase_0.93- 9
- Rttf2pt1_1.3.9
- png_0.1- 7
- latex2exp_0.5.0
- maps_3.4.0
- extrafontdb_1.0
- tensorA_0.36.2
- proto_1.0.0
- DEoptimR_1.0- 10
- proj4_1.0- 10.1
- RColorBrewer_1.1- 2
- yaml_2.2.1
- ash_1.0- 15
- bayesm_3.1- 4
- KernSmooth_2.23- 20
- utf8_1.2.2
- data.table_1.14.2
- dendextend_1.15.3
- lsa_0.73.2
- viridisLite_0.4.0
- ellipsis_0.3.2
- textshaping_0.3.5
- assertthat_0.2.1
- xfun_0.31
- ragg_1.1.3
- pkgconfig_2.0.3
- htmltools_0.5.2
- lifecycle_1.0.1
- DBI_1.1.1
- colorspace_2.0- 26
- arrow_13.0.0.1 (added in Nov 2023)


